src: 
  url: http://example.org/source/
  authToken: srcsecret

dst: 
  url: http://example.org/destination/
  authToken: dstsecret
  priority_id: 42
  status_id: 43
  tracker_id: 44
  project_id: 45
  mapping:
    alice: bob
    clara: dave
